### ISSUE TITLE
Ember 2.5 throws a deprecation notice on the use of Ember.merge()

### ISSUE THREAD

**Issue by kanongil** [ember-cli/ember-ajax#110]
```
DEPRECATION: Usage of `Ember.merge` is deprecated, use `Ember.assign` instead. [deprecation id: ember-metal.merge] See http://emberjs.com/deprecations/v2.x/#toc_ember-merge for more details.
        at HANDLERS.(anonymous function) (<snip>/assets/vendor.js:16523:7)
        at raiseOnDeprecation (<snip>/assets/vendor.js:16431:12)
        at HANDLERS.(anonymous function) (<snip>/assets/vendor.js:16523:7)
        at invoke (<snip>/assets/vendor.js:16539:7)
        at deprecate (<snip>/assets/vendor.js:16492:32)
        at Object.deprecate (<snip>/assets/vendor.js:26531:37)
        at merge (<snip>/assets/vendor.js:28682:22)
        at _getFullHeadersHash (<snip>/assets/vendor.js:67027:24)
        at options (<snip>/assets/vendor.js:67048:35)
```

**Comment by rwjblue** [comment]
Upgrade to 2.5.1, the deprecation was removed

**Comment by kanongil** [comment]
Ah, sorry I missed that. Seems that the "nuisance to our users" quote from https://github.com/emberjs/ember.js/pull/13344#issue-148748990 was spot on 😃.
