### ISSUE TITLE
Assertion failed: TypeError: promise.then is not a function

### ISSUE THREAD

**Issue by lolmaus** [ember-cli/ember-ajax#61]
Doing a `this.post()` and seeing this:

	Assertion failed: TypeError: promise.then is not a function
	    at null.handleActionPromise (http://localhost:4200/assets/vendor.js:204040:15)
	    at Object.applyStr (http://localhost:4200/assets/vendor.js:34117:20)
	    at Object.sendEvent (http://localhost:4200/assets/vendor.js:27633:28)
	    at notifyObservers (http://localhost:4200/assets/vendor.js:31176:25)
	    at Object.propertyDidChange (http://localhost:4200/assets/vendor.js:30972:5)
	    at Object.set (http://localhost:4200/assets/vendor.js:31458:48)
	    at exports.default._emberMetalMixin.Mixin.create.set (http://localhost:4200/assets/vendor.js:47227:31)
	    at setUnknownProperty (http://localhost:4200/assets/vendor.js:204058:12)
	    at set (http://localhost:4200/assets/vendor.js:31435:13)
	    at callbackHandler (http://localhost:4200/assets/vendor.js:204000:9)
	    at submitAnswer (http://localhost:4200/assets/bottle-rocket.js:1924:9)
	    at _emberViewsViewsView.default.extend.send (http://localhost:4200/assets/vendor.js:58260:54)
	    at _emberMetalMixin.Mixin.create.triggerAction (http://localhost:4200/assets/vendor.js:48132:29)
	    at _emberViewsViewsView.default.extend.sendAction (http://localhost:4200/assets/vendor.js:58244:14)
	    at click (http://localhost:4200/assets/vendor.js:204005:23)
	    at _emberRuntimeSystemObject.default.extend.trigger (http://localhost:4200/assets/vendor.js:58764:23)
	    at superWrapper [as trigger] (http://localhost:4200/assets/vendor.js:33723:20)
	    at Object._emberMetalMerge.default.handleEvent (http://localhost:4200/assets/vendor.js:59712:21)
	    at _emberViewsViewsCore_view.default.extend.handleEvent (http://localhost:4200/assets/vendor.js:61301:32)
	    at Object.Backburner.run (http://localhost:4200/assets/vendor.js:10767:25)
	    at Object.Backburner.join (http://localhost:4200/assets/vendor.js:10817:25)
	    at Function.run.join (http://localhost:4200/assets/vendor.js:31623:28)
	    at exports.default._emberRuntimeSystemObject.default.extend._bubbleEvent (http://localhost:4200/assets/vendor.js:57253:45)
	    at HTMLAnchorElement.<anonymous> (http://localhost:4200/assets/vendor.js:57195:25)
	    at HTMLBodyElement.jQuery.event.dispatch (http://localhost:4200/assets/vendor.js:4872:9)
	    at HTMLBodyElement.elemData.handle (http://localhost:4200/assets/vendor.js:4540:28)
	    at HTMLBodyElement.nrWrapper (http://localhost:4200/:54:12743)

Ember 1.13, ember-ajax 0.7.1.

**Comment by lolmaus** [comment]
Totally my fault.

**Comment by alexlafroscia** [comment]
Just curious, for future reference: what did you do wrong? Is there something `ember-ajax` could do to make the error messaging more clear?

**Comment by lolmaus** [comment]
It wasn't caused by ember-ajax even.

Instead of doing `asyncButtonCallback(emberAjaxPromise)` I accidentally wrote `asyncButtonCallback(asyncButtonCallback)`.
